id: alien-cloudify-3-orchestrator-volume
name: Cloudify 3 Orchestrator Plugin
version: ${project.version}
description: >
  Plugin that contains the Orchestrator for cloudify v3.
configuration_class: alien4cloud.paas.cloudify3.PluginFactoryConfiguration
component_descriptors:
  - bean_name: cloudify-orchestrator
    name: Cloudify 3 Orchestrator
    description: >
      An orchestrator that deploys applications on cloudify 3.x
      Make sure that you configure the url of the cloudify Rest API and the list of images and flavors.
